### ISSUE TITLE
Pokédex Drag & Drop Macro Creation doesn't work

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#106]
This is caused due to the category drag & drop mechanic which is implemented in an awkward way. 

I was already planning to redo this system but it'll have to wait till after 1.4, so until then new Pokédex macros will be unable to me created. Existing ones will still function.

**Comment by Theik** [comment]
For those who want to get it working until this is fixed, manually make a macro, put it to script and enter this:

`renderPokedex();

function renderPokedex() {
let targets = game.user.targets;
let iterator = targets .values();
let target = iterator.next();
if(!target) return;
target = target.value;
if(!target) return;

game.ptu.renderDex(target.actor.data.data.species)
}`

Then target the pokémon with the target tool and execute the macro.
