### ISSUE TITLE
Sort dex button (By Dex ID or Alphabetically)

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#121]
Sort trainer sheet dex

**Comment by MetaDK** [comment]
Could we also add a "sort" option like this but for the Items tab to alphabetically sort and possibly a lock option so they are forced back into their alphabetical order (or even using the lock button to lock whatever order it is set in, whether it is alphabetical or manual until it is ticked back off again)

You had also mentioned the possibility of adding a +/- on the items to help prevent dragging when trying to highlight quantities.

**Comment by dylanpiera** [comment]
Fully functional and added, could probably use a lick of paint in some future update, but I more so cared to add the functionality rn than to make it look pretty x)
