### ISSUE TITLE
Move categories/dividers

### ISSUE THREAD

**Issue by Strike2610** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#131]
Due to egg, tutor and TM moves not counting towards the 6 move limit, it would be nice if there were categories in the move list. Similar to the inventory categories.

**Comment by puresowns** [comment]
Moves are a Pokémon’s battle techniques and have the
biggest influence on their combat ability.
Pokémon may learn a maximum of 6 Moves from
all sources combined. However, certain Abilities and
Features may allow a Pokémon to bypass this limit.
A Pokémon may fill as many of its Move slots as it likes
with Moves from its Natural Move List. This includes
all Moves gained from Level Up, all Egg Moves, and all
Tutor Moves marked with an (N). However, no more
than 3 of a Pokémon’s Moves may be from TMs and
Move Tutors, with the exception of the Natural Tutor
Moves noted above. Any Feature that requires Tutor
Points to cause a Pokémon to learn Moves is considered
a Tutor.
If a Pokémon learns a Move via TM or Move Tutor that
it can later learn via Level Up, once the Pokémon has
the opportunity to learn it naturally, that Move becomes
counted as a “Natural” Move for the purposes of the
3-TM/Tutor Move Limit.
Unlike Pokémon, Trainers have no limit to the number
of Moves they may learn.

Page 200 of 1.05 Core

Be cool if they didn't count though

**Comment by dylanpiera** [comment]
> Moves are a Pokémon’s battle techniques and have the
> biggest influence on their combat ability.
> Pokémon may learn a maximum of 6 Moves from
> all sources combined. However, certain Abilities and
> Features may allow a Pokémon to bypass this limit.
> A Pokémon may fill as many of its Move slots as it likes
> with Moves from its Natural Move List. This includes
> all Moves gained from Level Up, all Egg Moves, and all
> Tutor Moves marked with an (N). However, no more
> than 3 of a Pokémon’s Moves may be from TMs and
> Move Tutors, with the exception of the Natural Tutor
> Moves noted above. Any Feature that requires Tutor
> Points to cause a Pokémon to learn Moves is considered
> a Tutor.
> If a Pokémon learns a Move via TM or Move Tutor that
> it can later learn via Level Up, once the Pokémon has
> the opportunity to learn it naturally, that Move becomes
> counted as a “Natural” Move for the purposes of the
> 3-TM/Tutor Move Limit.
> Unlike Pokémon, Trainers have no limit to the number
> of Moves they may learn.
> 
> Page 200 of 1.05 Core
> 
> Be cool if they didn't count though

Correct, Strike is specifically however talking about our game as I've homebrewed this rule out haha. 

Regardless, there are ways to go over the cap and it would still be nice to know how many moves are of a certain type as there are restrictions on how many non-level-up moves you can have.
