### ISSUE TITLE
Sentret is missing a Dex Entry

### ISSUE THREAD

**Issue by MetaDK** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#132]
Sentret is not within the Dex Entries compendium. As per your request, I was able to confirm that it is within the charactermancer and has its stats and all. It is simply missing from the Dex Entries to fill up a Pokedex. :)

Thanks again!

**Comment by dylanpiera** [comment]
Added in ca6fbc1d0d5399d644c1fd13eb674551ea4cc406
