### ISSUE TITLE
Berry Section/Pocket for the inventory list

### ISSUE THREAD

**Issue by MetaDK** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#134]
I have a player with a Portable Grower and is mass producing berries and even apricorns, so a Berries section to the item tab would be good to filter those out unless needed. (Besides, this just makes it look like the actual games too lol)

**Comment by dylanpiera** [comment]
You can create custom categories by opening up an item's edit window, scrolling down and changing the value of 'category'. 

After the first berry created it will then remember the category and allow you to drag & drop the rest.

If others would like this to be added as a default category we can do so, but I'm against it as we already have the 'food' category which kinda has the same function.

**Comment by dylanpiera** [comment]
As there have been no replies since that I'm closing this for now.
