### ISSUE TITLE
Tyrantrum Overland Incorrect

### ISSUE THREAD

**Issue by alexander-r-block** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#137]
Tyrantrum Overland is 7, but it comes up as 6 in game. Please ignore if this was a change made after PTU 1.05.

**Comment by dylanpiera** [comment]
The system is using the following dex as a source:
![image](https://user-images.githubusercontent.com/2012848/123215751-1e7dad80-d4c9-11eb-8c7e-27ea1698407e.png)

Where the overland is indeed 6
![image](https://user-images.githubusercontent.com/2012848/123215695-0d34a100-d4c9-11eb-8402-c5b5947776d5.png)
