### ISSUE TITLE
Archen "sky" capability missing

### ISSUE THREAD

**Issue by alexander-r-block** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#138]
PTU 1.05: Archen has "Sky 4", but this does not show on the sheets.

**Comment by dylanpiera** [comment]
The system is using the following dex as a source:
![image](https://user-images.githubusercontent.com/2012848/123215751-1e7dad80-d4c9-11eb-8c7e-27ea1698407e.png)

Which lists archen incapable of flight:
![image](https://user-images.githubusercontent.com/2012848/123215927-4bca5b80-d4c9-11eb-9e34-269f26435ed7.png)

Also if we look at Pokedex entries (Pokemon Y:) 
> Said to be an ancestor of bird Pokémon, they were **unable to fly** and moved about by hopping from one branch to another.

So this change makes sense
