### ISSUE TITLE
Prevent stacking Dex Entries

### ISSUE THREAD

**Issue by MetaDK** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#140]
When a player adds a Dex Entry to their sheet, they can add it several times. Would it be possible to run a simple "check" to see if its already present before adding it? And if it's already there, a popup saying, it's already there, or simply not adding it to the sheet? With 800+ mons, would limit additional useless clutter that can rack up with time.

Also, Ditto's Dex Entry has a typo, "they often gets details wrong while doing so." should simply be "they often get" ^_^

**Comment by dylanpiera** [comment]
This should already be the case, I'll confirm in a bit

**Comment by dylanpiera** [comment]
Indeed seems broken in latest update, will investigate.
