### ISSUE TITLE
Add an option to automatically approve the GM prompt for TransferOwnership, skipping the popup.

### ISSUE THREAD

**Issue by GSV-a-Nest-of-Kindled-Embers** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#150]
Add an option to automatically approve the GM prompt for TransferOwnership, skipping the popup.

There's no circumstance in which I as a GM would actually want to deny the request (barring accidental Pokeball throws at the wrong thing or something, but I'd rather handle undoing that manually than have to deal with the popups).

**Comment by dylanpiera** [comment]
@GSV-a-Nest-of-Kindled-Embers you're capable of adding this yourself.

**Comment by Ellamental2** [comment]
this is already implemented under combat settings

![image](https://user-images.githubusercontent.com/43385250/230362116-fa91f1a9-c02a-45c4-928b-890e7a368abb.png)
