### ISSUE TITLE
MEDIUM: Allow non-player-owned pokemon to have their Owner field manually set to NPC trainers, instead of forcing it to Wild

### ISSUE THREAD

**Issue by GSV-a-Nest-of-Kindled-Embers** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#157]
MEDIUM: Allow non-player-owned pokemon to have their Owner field manually set to NPC trainers, instead of forcing it to Wild

This is beginning to hard-block some automation on the GM side, which is important as I add automation for trainer features and utilities applying to owned pokemon and want to use them for gym leaders, enemy trainers, etc.

**Comment by dylanpiera** [comment]
Fixed in 19dc265f4799d2945bbfa7498a850709ab92d2c9
