### ISSUE TITLE
Unable to use many features in PTU-S on Foundry

### ISSUE THREAD

**Issue by Fyrecracker** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#159]
I am running the recent build of stable PTU-S as well as the most recent Foundry VTT build. 

I can't delete anything on anyones actor sheet.
I also can't edit the PTU settings. Nothing pops up. I see the button on the configuration settings bar but I can't get it to work.

Is this a common issue?

**Comment by dylanpiera** [comment]
The latest release is for 0.7.10, please update to the beta if using Foundry 9.

**Comment by Fyrecracker** [comment]
This is awesome. Updating it to the latest release worked out for foundry 9. I just can't save the PTU settings. I love the changes and working features for customization but is there a setting I am missing to be able to config the PTU stuff?

**Comment by dylanpiera** [comment]
Fixed in the latest beta
