### ISSUE TITLE
Suggestion: Add and Automate Egg Images

### ISSUE THREAD

**Issue by RinVindor** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#163]
Like the regular images for 'Mon it'd be great to have the ability to have a way to import eggs into a folder and use the same naming structures but for eggs. Maybe have them as a type off Item that has a Hatch Rate entry as well to track that info as well an entry for Egg Move List.

**Comment by dylanpiera** [comment]
I currently do not see added value in having a seperate 'egg' item with auto image generation.
I don't know of an image repository that has different egg sprites for all 800+ mons, as well as there not being any 'egg automation', so a description field on an item should suffice.

If you can elaborate the use case more we can think about adding this feature.
