### ISSUE TITLE
Can't delete anything I put on an actor's sheet

### ISSUE THREAD

**Issue by EleArtee** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#164]
It happens for both pokemon and characters. No matter how many times I press the trash icon, and no matter if is a move, ability, capability, feature or edge, I can't delete it. Is this a bug or something else?

**Comment by dylanpiera** [comment]
The latest release version only supports foundry 1.7.10. Please update to the beta for 0.8/v9 support.
