### ISSUE TITLE
Burn/Poison/"Action Based Tick" support for 2-Action Homebrew

### ISSUE THREAD

**Issue by rhykotsu** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#166]
Currently, games that use the Kindled Embers' Extra Action Homebrew that have afflictions that tick "per action" only tick once at the end of the turn.

Ideally, each time an action or Move is used, the afflicted pokemon would take a tick of damage. 

Alternatively, at the end of the turn, there could be a prompt (similar to the already existing one) that asks how many actions a pokemon took (for speed, instead of a box or dropdown menu, simply a button for one and a button for two actions would suffice).

**Comment by dylanpiera** [comment]
Good news, in the new next update action economy will be implemented. So adding an extra check for the 2nd action won't be a problem.
