### ISSUE TITLE
Cleanup /ptug and add more functionality akin to drag-drop

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#168]
> Matthias — 03/04/2022
Would it be possible to update ptug to automatically link the tokens? The same way it does with Dex drag out and quick insert?
Also ptug doesn't support webm tokens

/ptug needs a cleanup anyways and is behind in terms of functionality.

**Comment by Ellamental2** [comment]
is this still needed?
Personally I have never used ptug. I just use quickinsert or the dexentries compendium

**Comment by dylanpiera** [comment]
Yes, I use it a ton for quickly creating a bunch of mons for random encounter options.
