### ISSUE TITLE
Dex Experience does not calculate

### ISSUE THREAD

**Issue by Charbizard** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#171]
Made a new world, tried to add pokemon to the dex to trigger dex exp. Does not work.
![image](https://user-images.githubusercontent.com/98428555/157099201-aeed9c6a-0997-4bb6-aec0-e7e908c2455a.png)
![image](https://user-images.githubusercontent.com/98428555/157099246-14fc118e-a1a3-44df-8547-01b09aaf7815.png)
![image](https://user-images.githubusercontent.com/98428555/157099264-874569e9-6161-46bc-9224-83600768bc24.png)

**Comment by dylanpiera** [comment]
Fixed in 9c736edd7621b9863e1ba704f26fa5729372a6c4
