### ISSUE TITLE
Tick healing is not healing to full but instead applying an injury and then adding to temp hp

### ISSUE THREAD

**Issue by Charbizard** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#172]
![image](https://user-images.githubusercontent.com/98428555/157133128-fb1fa97f-a13a-43ec-a010-3d64a6db4b69.png)
![image](https://user-images.githubusercontent.com/98428555/157133148-e5df1814-898a-41f4-ac54-d1759cece6b7.png)
![image](https://user-images.githubusercontent.com/98428555/157133166-81f017a8-2c58-4fbf-bb22-fe670d6b31f9.png)
![image](https://user-images.githubusercontent.com/98428555/157133175-05841e34-66f8-4838-8e6f-bb38cf235dd4.png)
![image](https://user-images.githubusercontent.com/98428555/157133184-b94a6d5d-bab8-4518-aa5c-f400878f961c.png)

**Comment by dylanpiera** [comment]
Tick healing is a move master feature not of the main system.

However it has now been merged, but the tick healing has yet to be implemented. So when we re-implement it we'll have it work properly.
