### ISSUE TITLE
Uranium Pokemon (Nuclear-X) Do not work

### ISSUE THREAD

**Issue by Charbizard** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#175]
Generating with the Dex Entries any Pokemon that is "Nuclear-X" does not generate a Pokemon.

**Comment by dylanpiera** [comment]
Unable to reproduce. 

Are you sure you enabled them?
![image](https://user-images.githubusercontent.com/2012848/177334707-3c6cda7d-d759-46b3-bc51-06140e9f295d.png)
