### ISSUE TITLE
Add option to obscure effectiveness info in Sidebar

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#185]
Incognegro — 05/15/2022 Is there a way to obscure typing information on unowned pokemon? I.E. a pokemon my players have never seen before reveals what its weak/resistant too, despite not being in the dex

 Issue opened on Discord by AsheEon#0380

**Comment by Ellamental2** [comment]
approached here: https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/pull/204
