### ISSUE TITLE
BUG?: Wiki on https://ptufvtt.com blocks you out of everything when logged in

### ISSUE THREAD

**Issue by Muhsigbokz** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#197]
Step to reproduce:

1. Go on https://ptufvtt.com
2. Log In via Discord (as anyone who likely is not admin I guess)

Expected: I can still see the site as normal, with the parts that are publicly available.

What actually happens:
*you can't even log out*
![image](https://user-images.githubusercontent.com/101654076/172399499-89596614-c9f0-42be-8379-afb82aac408d.png)

Likely not interesting for you in the moment, but I guess all your accounts are admins and you won't know this until someone tells you <3

**Comment by dylanpiera** [comment]
Forgot to re-add the user group during migration. Fixed now.
