### ISSUE TITLE
Multi-form Pokémon

### ISSUE THREAD

**Issue by Strike2610** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#20]
An easy way to switch between the forms of Pokémon such as Rotom or Wormadam.

**Comment by dylanpiera** [comment]
Like a macro? You can set change the species, not?

**Comment by Strike2610** [comment]
A lot of things can change with different forms and I think it would be nice to make this say an easy dropdown.
Rotom for example also gains the relevant variant of struggle in four of it's forms.

**Comment by dylanpiera** [comment]
Feature for later in the Charactermancer. 

Meanwhile if you want you can make some macros and I can add them as a compendium to the system.
