### ISSUE TITLE
SUGGESTIONS: 'Power User' Character Mancer

### ISSUE THREAD

**Issue by Muhsigbokz** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#202]
As of now, it is stated that a Roll20 DnD5e style character mancer should be added to the system.

This character mancer is a guide that helps you step by step through character creation. It aids by explaining each step and making sure only legal options are listed at every step to lower the burden on the player. Likely rules are explained, examples listed, etc. This is great for players leaning more towards the casual side play and are not as rule savvy.

Another use case could be for experienced players with a specific concept in mind that want a tool to assist them quickly create a probably higher level character. I envision a tool that offers me in once big form all Feature and Edge slots of a character of max level and all Edges and Features. If I select a Feature like `Seize The Moment` (last Duelist Feature) and I drag it into the forms slot for my 11th level feat, it instead slots into the 13th level slot, and all prerequisites are slotted into their earliest possible slot. In this concrete example, something like this would happen:

| Feature          | Level                  | Edge         |
| ---------------- | ---------------------- | ------------ |
|  xxx                | 0 (Adept Skill)        | Adept Focus  |
|  xxx                | 0 (Novice Skill)       |              |
|  xxx               | 0 (Pathetic Skill)     |              |
|  xxx               | 0 (Pathetic Skill)     |              |
|  xxx               | 0 (Pathetic Skill)     |              |
| Duelist          | 1                      |              |
|                  | 1                      |              |
|                  | 1                      |              |
|                  | 1                      |              |
|                  | 1 (free Training)      | xxx          |
| xxx              | 2                      |              |
| xxx              | 2 (extra)              |              |
|                  | 3                      | xxx          |
| xxx              | 4                      |              |
|                  | 5                      | xxx          |
|                  | 5 (General or Stats)   | xxx          |
| xxx              | 6                      | Expert Focus |
| xxx              | 6 (Bonus)              |              |
|                  | 7                      | xxx          |
| xxx              | 8                      |              |
|                  | 9                      | xxx          |
| xxx              | 10                     |              |
| xxx              | 10 (Edge or stats)     |              |
| xxx              | 10 (Edge of not stats) |              |
|                  | 11                     | xxx          |
| xxx              | 12                     | Master Focus |
| xxx              | 12 (Bonus)             |              |
| Seize the Moment | 13                     | xxx          |
| xxx                | 14                     |               |
|         | 15                     |  xxx          |

When then dragging in `Divine Wind`, it would look like this. Likely with a popup or something else making clear that `Sacred Shield` can be exchanged with `Mystic Defense`.

| Feature            | Level                  | Edge          |
| ------------------ | ---------------------- | ------------- |
| xxx                | 0 (Adept Skill)        | Adept Focus   |
| xxx                | 0 (Novice Skill)       | Novice OccEd  |
| xxx                | 0 (Pathetic Skill)     |               |
| xxx                | 0 (Pathetic Skill)     |               |
| xxx                | 0 (Pathetic Skill)     |               |
| Duelist            | 1                      |               |
| Sage               | 1                      |               |
| Sacred Shield      | 1                      |               |
|                    | 1                      |               |
|                    | 1 (free Training)      | xxx           |
| xxx                | 2                      | Adept OccEd   |
| xxx                | 2 (extra)              |               |
| Sage's Benediction | 3                      | xxx           |
| xxx                | 4                      |               |
|                    | 5                      | xxx           |
|                    | 5 (General or Stats)   | xxx           |
| xxx                | 6                      | Expert Focus  |
| xxx                | 6 (Bonus)              |               |
|                    | 7                      | xxx           |
| xxx                | 8                      | Expert Occ Ed |
|                    | 9                      | xxx           |
| xxx                | 10                     |               |
| xxx                | 10 (Edge or stats)     |               |
| xxx                | 10 (Edge of not stats) |               |
|                    | 11                     | xxx           |
| xxx                | 12                     | Master Focus  |
| xxx                | 12 (Bonus)             | Master OccEd  |
| Seize the Moment   | 13                     | xxx           |
| xxx                | 14                     |               |
| Divine Wind        | 15                     |  xxx          |

---------------

Implementation wise, as the target audience are people knowing the system that want aid to quickly create characters, there is likely less work on the UI side. Also, the necessary logic of prerequisite checking is also needed for the Roll20 DnD5e style character mancer.

Obviously, this is no full design document with all features and all behavior, but it should make the concept clear.^^

Discussion, optinions?

**Comment by dylanpiera** [comment]
Love the idea but not going to target for this quite yet, so jus tlike the other 'maybe later' issues that are far in the future closing it for now.
