### ISSUE TITLE
Delete button doesn't work for moves, abilities, edges and more

### ISSUE THREAD

**Issue by joosh98** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#206]
In a Pokemon or character sheet, the delete button does not work.

Observed for the following:
Pokemon sheet: moves, abilities, edges
Character sheet: items, features, edges

https://i.gyazo.com/d70170a6658c57d6b04be02ba2c8918e.mp4

**Comment by dylanpiera** [comment]
Please update to the beta branch
