### ISSUE TITLE
Add custom type images

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#216]
Allow players to set a folder for custom type images.

**Comment by Muhsigbokz** [comment]
On it.

**Comment by Muhsigbokz** [comment]
Is it sufficient to have the Images for Custom Types follow the same strict naming and format rules? That being `/some/path/[CaseSensitiveTypeNAme]IC.webp`?

**Comment by dylanpiera** [comment]
Yeah that'd be perfect. Just make it so the base path is a setting.
