### ISSUE TITLE
Allow dice for damage

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#218]
allow adding a die expression like 2d6 into bonus damage (both the move field and the shift-click damage dialogue) to allow for things like rock head and defeatist

 Issue opened on Discord by Incognegro#1079

**Comment by Muhsigbokz** [comment]
On it.

**Comment by dylanpiera** [comment]
Partially fixed; The Ad-hoc menus now support it. Bringing support to the character sheet requires more changes. Bumping down priority.
