### ISSUE TITLE
BUG: The icon buttons for targeted Attacks Damage ignores the Crit toggle.

### ISSUE THREAD

**Issue by Muhsigbokz** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#228]
The target (Unown) has 5 Defense.

Here using the Circle
![image](https://user-images.githubusercontent.com/101654076/178553350-684bbb05-bcf6-4d94-a2e7-753d56a40a20.png)

Here the `APPLY` button
![image](https://user-images.githubusercontent.com/101654076/178553557-ba3037e3-7ddf-46a4-910c-7102ac3faf95.png)

**Comment by dylanpiera** [comment]
This was fixed in latest version, are you sure you updated?

**Comment by Muhsigbokz** [comment]
Update: is the case for all of these buttons
![image](https://user-images.githubusercontent.com/101654076/178556123-693da371-eaed-4e5f-9063-b0d16a3054b3.png)

**Comment by dylanpiera** [comment]
The individual buttons don't work but mass apply does.

**Comment by dylanpiera** [comment]
Fixed in 29ecb594721992d026e60352ecccb31ec523e322
