### ISSUE TITLE
Add Mising Capability Altering Abilities

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#24]
Double check abilities that modify capabilities, f.e., sprint is missing.

**Comment by dylanpiera** [comment]
In the same boat, Water Bubble isn't applied to resistances.

**Comment by CheffOfGames** [comment]
Also, Sacred Bell doesn't resist Dark and Ghost

**Comment by dylanpiera** [comment]
Added Sprint in V0.0.42, will add the rest soon.

**Comment by dylanpiera** [comment]
Fixed in V1.0
