### ISSUE TITLE
Re-do item sheets

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#244]
Item sheets have not received any love in forever.

They need a couple updates:
- Niche functionalities need to be fixed or removed (f.e. rolling from inside a move)
- html -> hbs
- HTML should be cleaned up as classes instead of styles

Maybe even consilidate the sheets.

**Comment by Ellamental2** [comment]
Could we also have options for items to have attacks when clicked or hp? I recently had a session where the players used a bug catching net and this would have been useful
