### ISSUE TITLE
Various Image Issues

### ISSUE THREAD

**Issue by alexander-r-block** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#250]
- Alola and Galar Pokemon Sprites do not pull correctly using dex drag-in feature (the base form image is used as the sprite). I tested with with a fresh install with no modules enabled.
- Missing Z-Crystal Images
	- Aloraichium Z
	- Decidium Z
	- Eevium Z
	- Incinium Z
	- Kommonium Z
	- Steelium Z
	- Waterium Z
- Other items missing images (I tried to only include items with Global Link images available on Bulbapedia)
	- Black Sludge
	- Choice Band
	- Choice Specs
	- Normal Plate
	- Expert Belt
	- Flame Orb
	- Focus Band
	- Focus Sash
	- Honey
	- Iron Ball
	- Lagging Tail
	- Lucarionite
	- Mental Herb
	- Power Herb
	- Safety Goggles
	- Shell Bell
	- Smoke Ball
	- TM29 - Psychic
	- Toxic Orb
	- White Herb
	- Zygarde Cube

**Comment by dylanpiera** [comment]
@GSV-a-Nest-of-Kindled-Embers you want to take care of this?
