### ISSUE TITLE
STAB doesn't work on mons with 3+ typings

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#254]
Only the first 2 types are kept in mind; it ignores the rest.

 Issue opened on Discord by AsheEon#0380

**Comment by Ellamental2** [comment]
I've been having a look at this,

I think i've found a solution but it's one of those that looks too simple to be correct.

in ptu.js line 430
change `    move.stab = move.owner?.type && (move.owner.type[0] == move.type || move.owner.type[1] == move.type || move.owner.type[2] == move.type);`
to  `    move.stab = move.owner?.type && (move.owner.type[0] == move.type || move.owner.type[1] == move.type || move.owner.type[2] == move.type || move.owner.type[2] = move.type)`

and in moves-component.js a similar change to line 182
`moveData.stab = moveData.owner?.type && (moveData.owner.type[0] == moveData.type || moveData.owner.type[1] == moveData.type);` to `moveData.stab = moveData.owner?.type && (moveData.owner.type[0] == moveData.type || moveData.owner.type[1] == moveData.type || moveData.owner.type[2] == moveData.type);`

**Comment by dylanpiera** [comment]
Fixed
