### ISSUE TITLE
pokemons in trainer sheet

### ISSUE THREAD

**Issue by eunaumtenhoid** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#256]
it would be very interesting if it were possible to add pokemon slots in the trainer's sheet, to show which pokemons he is carrying at the moment when clicking on the pokemon would open the same sheet, as in video games for example

**Comment by dylanpiera** [comment]
Hi @eunaumtenhoid 

Personally I don't see much use to this feature, as the sidebar already shows the pokemon someone has in their party. 
(assuming trainer actor & pokemon are in the same box, and the pokemon their owner is set to said trainer actor).

And double clicking them already has the functionality to then open their sheet (single click selects them on the scene)
