### ISSUE TITLE
Item Consumption

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#274]
have items like Potions actually heal the target and reduce from inventory

 Issue opened on Discord by Nexus Flamehart#0001

**Comment by dylanpiera** [comment]
Quite simple feature for someone that wants to help out to start working on, I'm not planning to prioritize it myself.

**Comment by Ellamental2** [comment]
I am looking at this

**Comment by Ellamental2** [comment]
related: #244
