### ISSUE TITLE
Token linked to a sheet doesn't update upon Evolution

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#291]
The token linked to a mon sheet doesn't update to match current evolution. To recreate issue, generate a random mon that has an Evolution stage. Give XP on sheet and go via Charactermancer to make it evolve. When dragging that sheet onto the map, the token doesn't update to the new evolution form. It does update in the sidebar, however it doesn't update when you drag it onto the map.

 Issue opened on Discord by Joooooosh🐉#2354

**Comment by Ellamental2** [comment]
The active tokens and prototype token will now update if evolved through the level-up form
