### ISSUE TITLE
Maneuvers should have Descriptions

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#294]
Please make it so Manuevers describe the actions when hovered over as like Moves do

 Issue opened on Discord by Nexus Flamehart#0001

**Comment by dylanpiera** [comment]
@Ellamental2 didn't you do this?

**Comment by Ellamental2** [comment]
I'm fairly sure I did. Will check when I'm at my pc.

Currently gives the effect. Do you mean like a quick snippet so for sprint "spend your action to move faster" instead of the full effect?

**Comment by Ellamental2** [comment]
issue was caused by putting effect into system{} so had to change the title of the buttons to `{{system.effect}}`
