### ISSUE TITLE
Formatting error

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#295]
It looks like with the recent update some formatting error occurred where the Name and Origin/Pre-reqs are all out of wack on each of the pages

 Issue opened on Discord by Charbizard#8233

**Comment by Charbizard** [comment]
![image](https://user-images.githubusercontent.com/98428555/212151857-ba6f4972-b5ed-455c-95aa-564b4152ee53.png)

**Comment by Ellamental2** [comment]
Looks like a stray } will have a look shortly
