### ISSUE TITLE
Replace Last Chance / Type Brace automation

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#301]
Instead of using the Name of the ability check the effect; as well as renaming the system versions to read "The user gains Last Chance/Type Brace (Type)"

 Issue opened on Discord by AsheEon#0380

**Comment by dylanpiera** [comment]
Awaiting PTR changes.

**Comment by joosh98** [comment]
Just realised I duplicated this ticket with https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/issues/401 - my bad.

What aspect of Type Braces needs amending?
