### ISSUE TITLE
Notes Section for Pokemon

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#303]
Currently, I keep track of when a Pokemon is caught for trainers along with a little blurb like the video games do. This allows trainers to track how long they've had them and other cool information for them in regards to wanting to interact with the Pokemon. Would it be possible to add a small notes section onto the tabs instead of in the top bar where it's easily lost? Maybe something like the Trainers get.

 Issue opened on Discord by Charbizard#8233

**Comment by Charbizard** [comment]
![image](https://user-images.githubusercontent.com/98428555/214078649-e7befc60-8a0b-47ac-84bf-0eaebc2e3173.png)

**Comment by dylanpiera** [comment]
As I posted in Discord:
> The notes section was specifically put in the top bar because I didn't want to clog up more space on the Pokemon Sheet-- the extra tab is already rather full so I'm not keen on adding more to it, and an entire tab for notes I don't think is quite yet warranted

If there's more people that are interested in a sole tab for notes on pokemon sheets, make them reach out to me either here or on discord and if we have enough people that think it's worth it, we can go ahead with this request.

Leaving it open for a week before closing it as unresolved.

**Comment by Ellamental2** [comment]
Created an option. This ticket can be closed. Final decision on whether to include the section will be made by Ashe on the PR.
