### ISSUE TITLE
Rename Digestion Buff in Mon & Trainer sheet to Food Buff

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#307]
Data's Homebrew Misc Errata document: "Digestion Buffs are now called Food Buffs". Could we change the field "Digestion Buff" on Mon and Trainer sheets to reflect this?

 Issue opened on Discord by Joooooosh🐉#2354

**Comment by joosh98** [comment]
Page 18 of 1.05_Datas_Homebrew_Misc_Errata_Document.pdf
