### ISSUE TITLE
Underdog's Strength does not apply

### ISSUE THREAD

**Issue by Exonaut** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#331]
The Underdog's Strength +1 to Base Stats of a Pokemon does not apply itself.

Tested with system version 3.2.2.1

**Comment by dylanpiera** [comment]
Pretty sure that's because it was never implemented but can be done through effect.

**Comment by Exonaut** [comment]
> Pretty sure that's because it was never implemented but can be done through effect.

Hmm a player stated that it did not work anymore. So I thought it did before. Either way, an automatic implementation would be nice, even if it isn't a new bug.
