### ISSUE TITLE
Visible moves

### ISSUE THREAD

**Issue by CheffOfGames** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#35]
Be able to see party members moves

**Comment by drakodra** [comment]
isn't this more of a permissions issue?
while i was testing i set the permission on sheets to 
Everyone is an Observer
and one player is an Owner

**Comment by dylanpiera** [comment]
It is, but observers should be able to view the complete sheet imo.

So I'm gonna see if I can add that later.
