### ISSUE TITLE
Set default Nature to a neutral value

### ISSUE THREAD

**Issue by DarthWolf13** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#36]
Set the Nature upon Pokémon creation to either Composed, Hardy, Docile, Bashful, Quirky or Serious.
This makes it easier to see the true base stats of a species in Foundry.

**Comment by dylanpiera** [comment]
![Screenshot_20201107-204825](https://user-images.githubusercontent.com/2012848/98450158-a7162c00-213a-11eb-8e19-bbaca8963b10.jpg)
🤔

**Comment by dylanpiera** [comment]
I'll have a quick look at it later tonight but it's already setup to do that, not sure if I can fix it if it isn't already working.

**Comment by dylanpiera** [comment]
I'm silly, it says curious not composed, my bad.
