### ISSUE TITLE
Feats not going to chat from compendium

### ISSUE THREAD

**Issue by Arisphadrel** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#365]
As it says. In order to call Feats over to the chat, they have to be in a character sheet. They won't naturally pop up into the chat. Not sure if this is intended or not, but would be nice to be able to pop up a Feat from the Feat Compendium and reference it in the chat for players when they wanna rule lawyer.

**Comment by dylanpiera** [comment]
Nothing to do with Compendium, the feat's to-chat function was just broken. Fixed in next beta.
