### ISSUE TITLE
Bewear dex dragin abilities incorrect

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#374]
gives 'fluffy charge' instead of 'fluffy'

 Issue opened on Discord by Ellam#6478

**Comment by Ellamental2** [comment]
![image](https://user-images.githubusercontent.com/43385250/233843245-2e67a734-086c-4260-8207-538745a41860.png)
![image](https://user-images.githubusercontent.com/43385250/233843256-ac61acab-ac5d-40e9-8eed-f68cb8876a86.png)
![image](https://user-images.githubusercontent.com/43385250/233843260-8b6aff67-d8fa-4b52-9b07-9fd43f58077c.png)

**Comment by dylanpiera** [comment]
Fixed in c0c0521540ece362a50b90ff7ab178b925458e91
