### ISSUE TITLE
bonemerang animation

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#391]
jb2a has a really good animation for literally throwing a bone. This feels like it should be the animation for bonemerang

 Issue opened on Discord by Ellam#6478

**Comment by dylanpiera** [comment]
@Ellamental2 dunno if we'll still be using this with for AA?

**Comment by Ellamental2** [comment]
Players can make their own animation with AA and share them so this will no longer be an issue
