### ISSUE TITLE
Fix Burmy Line

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#394]
https://discord.com/channels/748601513835888682/1109635702251065444/1109746657106591775

 Issue opened on Discord by AsheEon#0380

**Comment by joosh98** [comment]
Resolved in:
https://github.com/pokemon-tabletop-reunited/PTR-Data/commit/a96f4db610a3a3a80089d42c9794264264a040d1
