### ISSUE TITLE
Speed Stat Ace adds Movement Capability

### ISSUE THREAD

**Issue by DarthWolf13** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#40]
Agility Training gives + 1 to Movement Capabilities.
There might be more things that give a flat bonus.
Keep in mind that it wont change a capability from 0 to 1.

**Comment by dylanpiera** [comment]
#12 already covers training bonuses, unless there are a lot of things that add flat movement that aren't already covered by the system (f.e. moves and abilities are already covered) this field is unnecessary

**Comment by dylanpiera** [comment]
The only thing that isn't already covered by some other feature of the system is the Type Ace's Stat Strategem Speed bonus.

Add this as a class specific feature later down the line.
