### ISSUE TITLE
Potential change of Last Chance effect desc

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#401]
https://discord.com/channels/748601513835888682/1053753246025527386 f.e. "Focus" (last chance fighting)'s description is "the user gains last chance (fighting)". potentially change as per disc chat

 Issue opened on Discord by Joooooosh#2354

**Comment by joosh98** [comment]
This is now resolved in PTR-Data:
https://github.com/pokemon-tabletop-reunited/PTR-Data/commit/757edcbe594b333ca8a03149638309357956cc6e
