### ISSUE TITLE
Wake up

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#403]
add awakening item as it's missing from system & ptr data

 Issue opened on Discord by asheeon#0000

**Comment by joosh98** [comment]
Added Awakening to PTR Data. Interestingly it wasn't in the Basic Restoratives table in the Core Book. I added it for 200 Poke which is in line with Antidote, Paralyze Heal, Burn Heal, Ice Heal.

**Comment by dylanpiera** [comment]
Added in A15
