### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by theunknownmegaverse** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#405]
This is the error I get 

Error: System validation error: packs: 0: type: may not be undefined 1: type: may not be undefined 2: type: may not be undefined 3: type: may not be undefined 4: type: may not be undefined 5: type: may not be undefined 6: type: may not be undefined 7: type: may not be undefined 8: type: may not be undefined 9: type: may not be undefined  10: type: may not be undefined 11: type: may not be undefined

**Comment by dylanpiera** [comment]
PTR only supports foundry V10

Foundry v11 update is planned within next 2 months.
