### ISSUE TITLE
Add Walk It Off Ability

### ISSUE THREAD

**Issue by DarthWolf13** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#41]
The Community Patch grants the Walk It Off feature from the Enduring Soul Class to Pokémon as an Ability.

**Walk It Off**
_Daily – Standard Action_
Effect: 
You may remove one Injury from yourself, and regain 1/4th of your maximum Hit Points. This Injury removal doesn't count against the natural healing limit on Injuries each day. Use of Walk It Off counts as Taking A Breather for any Features, Abilities, and Moves(but not Status Afflictions or other conditions).

**Comment by dylanpiera** [comment]
@DarthWolf13 Do you mean the 'PTU 1.05 Editation' document? 

I'm not planning on adding community homebrew errata to the default compendium.

It can still be manually added as an ability to any world though that uses that community errata, and if used in multiple games it can be stored in a custom compendium and saved to the foundry installation.
