### ISSUE TITLE
Adaptability doesn't affect STAB

### ISSUE THREAD

**Issue by drakodra** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#42]
As the title says, Adaptability doesn't change the damage on stab moves as it should
the normal adaptability increases the db by 1 while the playtest adaptability adds a flat 1d10 to the damage

**Comment by dylanpiera** [comment]
That's correct, right now I'm not planning to add it for V1, however the ability to add flat modifiers _will_ be added before the V1 release

**Comment by dylanpiera** [comment]
Added in next beta.
