### ISSUE TITLE
Text Box Jumps up

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#435]
I got proof now

 Issue opened on Discord by charbizard#0000

**Comment by Charbizard** [comment]
![image](https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/assets/98428555/6261e810-841a-4bb9-ba9d-90b126aa96c8)
![image](https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/assets/98428555/b7f31cf8-3217-48f6-b0bd-4d313275dc61)

**Comment by dylanpiera** [comment]
Prob an issue with a module, I feel like we discussed this 3 weeks ago but I'll have to check it again later.
