### ISSUE TITLE
Homebrew Mons breaking in level up

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#436]
Level up screens are repeatedly opening without clicking, abilities are appearing as invalid.

 Issue opened on Discord by charbizard#0000

**Comment by Charbizard** [comment]
![image](https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/assets/98428555/cf5acc91-cc3f-44ff-9d62-425d3a9472cc)

**Comment by dylanpiera** [comment]
This is due to gen 9 import (pinged you on discord)
