### ISSUE TITLE
Add Basic Ranged Attack Automation

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#491]
see title

 Issue opened on Discord by asheeon#0000

**Comment by Tinkastrong** [comment]
- Should Normal-Typed Basic Ranged attacks be possible? If so, are they still only Physical or gain the option to be Special as well?

**Comment by dylanpiera** [comment]
> * Should Normal-Typed Basic Ranged attacks be possible? If so, are they still only Physical or gain the option to be Special as well?

That's Telekinetic.

**Comment by Tinkastrong** [comment]
Should Basic Ranged Attacks removes the Melee variants of Struggles and only make the Ranged ones appear in a sheet, or put them additionally in there?
