### ISSUE TITLE
Look into capability keywords being ignored

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#500]
https://ptb.discord.com/channels/748601513835888682/786196076285657159/1165690213914386573

 Issue opened on Discord by asheeon#0000

**Comment by dylanpiera** [comment]
This restriction can probably be removed but needs to be double checked

**Comment by Tinkastrong** [comment]
Maybe while this is being done, imho the modifier `system.modifiers.capabilities.all` would be better renamed `system.modifiers.capabilities.allMovement`.

**Comment by Tinkastrong** [comment]
`.../pokemon/document.js:PTUPokemonActor:_calcCapabilities()` gets called twice for every time an actor get updated. Assume an actor that has exactly one Rule to increase `system.modifiers.capabilities.overland` by `10`.
Inside the `_calcCapabilities()` `this.system.modifiers.capabilities["overland"]` behaves as follows when changing the Phase of the Rule

```
Phase                  Call 1       call 2
beforeRoll             undefined    undefined
afterDerived           undefined    10
default                10           10
beforeDerived          10           20
```
I assume that the `20` for `beforeDerived` is a fault that needs fixing, right?

CallStack tells me that the calls stem from `PTUActor:prepareData()`
```js
    prepareData() {
        this.constructed = false;
        // CALL 1
        super.prepareData();
        this.constructed = true;

        // Call post-derived-preparation `RuleElement` hooks
        for (const rule of this.rules) {
            rule.afterPrepareData?.();
        }
        // CALL 2
        this.prepareDerivedData();
        
        // and more...
```

This came up when trying to fix the capability keyword issue and is likely worth it's own issue, right?
