### ISSUE TITLE
UUID link in effect text doesn't show on attack roll

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#503]
see title

 Issue opened on Discord by asheeon#0000

**Comment by Tinkastrong** [comment]
I tried to tackle this myself, but to no avail thus far.
Looking at https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/blob/a4e2aee4cf831ea845c4a5af172cb0200519c43b/src/module/item/base.js#L415 and https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/blame/a4e2aee4cf831ea845c4a5af172cb0200519c43b/src/module/system/check/rolls/attack-roll.js#L70 , the point where the HBSs are rendered, both results still contain the `@UUID[a.b.c]` string, not changed into proper HTML.

For the sake of it I also fiddled with the `.hbs` files. Anywhere I put the item effect text in the attack-roll file, it result in the `@UUID[]` string in chat. Anywhere I put it in the `chat.items.hbs` it would become proper HTML.
