### ISSUE TITLE
Level Up Form refreshes Foundry in Librewolf

### ISSUE THREAD

**Issue by Bomb-Bard** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#541]
When attempting to navigate the level-up form, hitting submit causes the browser page to refresh, and does not save any changes made from level up. Currently using Librewolf browser (Firefox-based). Attempting a level-up in Chrome succeeds as expected.

**Comment by dylanpiera** [comment]
It's because some css features we use are locked behind feature flags in Firefox.

Enable :has support and it'll work fine.
