### ISSUE TITLE
Grass Elementalist (CR) correction

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#557]
Update effect and text for "Green Path", update effect text for the three ranks of "Nature's Embrace" (change 2 Moves to 3 Moves)

 Issue opened on Discord by titaniumdragoonneo#0000

**Comment by Muhsigbokz** [comment]
wiki fixed

**Comment by Muhsigbokz** [comment]
compendium fixed
