### ISSUE TITLE
Performance issue on player load with large number of custom Pokemon that they do not own

### ISSUE THREAD

**Issue by caffyn** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#56]
If there is a large (observed with ~75) number of Pokemon with custom species that are not owned by a player, then when that player loads into that game Foundry crawls to a halt for a period of time (observed average 30-45 seconds depending on number of players), and Foundry debug logs show considerable output of the following type:

```
{"message":"Compacted database file for actors","level":"info","timestamp":"2021-01-30 07:22:15"}
```
Console log shows matching following messages:
```
FVTT PTU | Triggering Custom Species Refresh with arguments: undefined
```
If the player is given ownership of all actors, behavior disappears. This is not seen when GMs are loading page. 

Behavior goes away when line 74 of `custom-species.js` is modified as follows, although the replacement debug messages repeat a considerable number of times: 

```
 72     await game.actors.filter(x => x.data.type === "pokemon" && (x.data.data.isCustomSpecies || x.data.data.typing     === undefined)).forEach(async (x) => {
 73         if(x.permission >= 3)
 74 console.log("replacement debug message")
 75             //await x.update({timestamp: Date.now()})
 76         else
 77             await game.socket.emit("system.ptu", "ReloadGMSpecies")
```

I'm not certain if my "fix" is a good idea, but I have enough backups that it's being tested in my game at this time.

**Comment by caffyn** [comment]
Forgot details:
Foundry 0.7.9
PTU 1.0.0
Ubuntu 18

**Comment by dylanpiera** [comment]
@caffyn Could you do me a favor and test the following:
- Try logging in as a player without permissions on those actors, while no DM is logged in.

Does the issue still persist?

I'm 90% sure what the issue is, and wow that's a pretty bad mistake I made. But I'd like to confirm it.

**Comment by dylanpiera** [comment]
Also if you wanna try a more optimal fix, replace line 72 to 77 with:
```js
await game.actors.filter(x => x.data.type === "pokemon" && (x.data.data.isCustomSpecies || x.data.data.typing === undefined)).forEach(async (x) => {
        if(x.permission >= 3)
            await x.update({timestamp: Date.now()})
        else {
            await game.socket.emit("system.ptu", "ReloadGMSpecies");
            return;
        }
    })
```

**Comment by dylanpiera** [comment]
I've released a patch on the beta branch that should fix this behavior. I'll be able to test this myself some more later, but do feel free to try it out and let me know if you experience any other difficulties with this patch.

**Comment by caffyn** [comment]
@dylanpiera : Behavior not reproducible if there's only a player logged in. Behavior resumes the moment I open a session as GM. Looks to be a match for the behavior you suspect. 

Initial testing looks fine with your version of the fix, but next session isn't until Friday so I can't 100% confirm no side effects under player load until then. I'm not aware of a way to move an established game to the beta branch of the system, so I'll stick to the custom patch for the moment.

**Comment by dylanpiera** [comment]
You can install the beta branch by installing the system in foundry using this url:

`https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/raw/development/system.json`

If you already have the system installed it'll update to the beta branch.

**Comment by caffyn** [comment]
OK, I think I did something dumb in testing. The one-off change you gave doesn't seem to address this after all in my "production" instance. Beta branch works fine, though, so I'll use that instead.
