### ISSUE TITLE
Compendium Browser Styling - Feats - Class Capitalization

### ISSUE THREAD

**Issue by Muhsigbokz** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#582]
![image](https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/assets/101654076/3a6ae6aa-91ef-446f-a549-e5e03c306748)

Should be `Ace Trainer` on the right, and `Ace Trainer [CR]` on the left.

**Comment by dylanpiera** [comment]
Fixed in 4.0.7
