### ISSUE TITLE
activateListeners modifies rendering

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#593]
https://discord.com/channels/748601513835888682/930949326228832266/1192795181297192960

 Issue opened on Discord by muhsigbokz#0000

**Comment by Muhsigbokz** [comment]
**Prolly a Bug**

__Background__: I did not yet figure out how another for enriching than assigning something to  `.innerHTML`. This kills all Listeners on that HTML element. That impacts ie `@UUID[]{}` links. They are in the same HTML element as my non-enriched stuff and get done before my code. This deletes their listeners, keeping them looking good but nothing happens during clicking. I am not aware of putting something in the middle of the html and not deleting the listeners.

So I edit the innerHTML and then call `sheetObject.activateListeners()` again. All got deleted, so they should not be double.

There are no double listeners, BUT I think I found an Error now causing a Bug. `ptu:src/module/item/sheet/sheet.js:PTUItemSheet.activateListeners:109` calls `ptu:src/util/tags.js:taggify`. `taggify()` manipulates the dom. Thus, it should not be called from within `foundry:client/apps/app.js:Application.activateListeners` Is it should be called after rendering.

```  
/**
 * After rendering, activate event listeners which provide interactivity for the Application.
 * This is where user-defined Application subclasses should attach their event-handling logic.
 * @param {JQuery} html
 */
activateListeners(html)
```

The resulting Bug causes all Tagified input/displays to be messed up such that there is one "sub-bar" for each call of `taggify()`.
