### ISSUE TITLE
Add a Legendary bool to species entries

### ISSUE THREAD

**Issue by GSV-a-Nest-of-Kindled-Embers** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#61]
For the purpose of capture rate calculations (in current macro scripts and also for future in-system automation), please add a method of storing whether or not a Pokemon species is Legendary to species entries (and the interface for creating/editing custom species).

**Comment by dylanpiera** [comment]
Anyone can pick this up by editing [/module/data/species-data.js](https://raw.githubusercontent.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/4622d38f239d3acf4a8daf711b855fa9c9547dca/module/data/species-data.js) and either sending it to me, or making a Pull Request

**Comment by dylanpiera** [comment]
Added in 1.3.1
