### ISSUE TITLE
Add a Trainer field/link to Pokemon sheets

### ISSUE THREAD

**Issue by GSV-a-Nest-of-Kindled-Embers** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#62]
For the purposes of macro scripting and future in-system combat automation, please add a field on Pokemon sheets that can hold a reference to a Trainer sheet.

Many Pokemon moves/capabilities/etc may be modified by that Pokemon's Trainer's features/etc, and establishing that link explicitly unblocks a lot of potential automation scripting.

**Comment by dylanpiera** [comment]
Added the functionality in such a way that it only shows Characters that:
- The Pokemon's owner(s) has as controlled characters
  - If no controlled character, any characters they own.
