### ISSUE TITLE
Add an option for Pokemon sheets to use Trainer skills

### ISSUE THREAD

**Issue by GSV-a-Nest-of-Kindled-Embers** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#64]
Many campaigns have Pokemon gaining and using skills (and Trainer Features/Edges/etc) as if they were Trainers, or in some cases using skills based off their Trainer's ranks.

I think the best way to support this kind of thing (barring a much more complicated Pokemon-Trainer hybrid sheet), would be to have a "Use Trainer's Skills" checkbox on Pokemon sheets that overrides the species data for skills and just copies the skills of the linked Trainer sheet (in conjunction with the Trainer field enhancement request I've raised here: #62 )

**Comment by dylanpiera** [comment]
> or in some cases using skills based off their Trainer's ranks.
Is this something caused by abilities from the core book or is this all homebrew?

**Comment by GSV-a-Nest-of-Kindled-Embers** [comment]
Technically homebrew (for instance, the current campaign I'm playing in has trainers in a cyberpunk world remote 'pilot' their pokemon, or any campaign based off the Mystery Dungeon series where there aren't any humans, but civilizations of Pokemon), though the _Do Porygon Dream of Mareep_ PTU suppliment has a section on Pokemon as Trainers.

Alternatively, if you don't want to deal with actually copying from another sheet, just some way to overwrite Pokemon skills instead of being forced to use the species values would be fine; possibly better in being more flexible.

**Comment by dylanpiera** [comment]
I see where you're coming from but the current solution to editing skill values of a species is by making a custom species version of it and then editing the skills where applicable. 

Adding a whole extra U.I. seems a bit excessive just for overwriting skill stats.
