### ISSUE TITLE
Bug: Hit points stop at 0 when entered through token bar math, while PTU should allow negative hit point values.

### ISSUE THREAD

**Issue by GSV-a-Nest-of-Kindled-Embers** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#67]
Bug: Hit points stop at 0 when entered through token bar math, while PTU should allow negative hit point values.

**Comment by dylanpiera** [comment]
Fixed in f168cffdc2807ebce495a4276cdec61beb3f4a6f
