### ISSUE TITLE
Fix Trainer Overland Calculation

### ISSUE THREAD

**Issue by DarthWolf13** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#68]
Calculation is
3 + ((Ath + Acr) / 2)

PTU always rounds down.
The current system rounds up

**Comment by dylanpiera** [comment]
Current system rounds down

[See Line 15](https://www.github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/tree/master/module%2Factor%2Fcalculations%2Fcapability-calculator.js)
