### ISSUE TITLE
The shiny auto generation text lies a bit. (minor)

### ISSUE THREAD

**Issue by RcwynnDM** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#686]
So in toggle generation, the shiny rate text reads "Default Species Drag In Shiny Chance (%)" that kinda a lie because when you ready like that you expect that anything in the box will be turned into a percentage Example: if you put 1 in the expected value would be 1%, but it's not it actually 100% chance so the default rate of .2 is actually 20%. I want to know if this was intentional or just an error in text.

![image](https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/assets/157905306/389c6465-c79b-4482-9a43-9f2d9c2191e3)

**Comment by dylanpiera** [comment]
"Intentional" to a degree, 100 == 100%, 80 == 80% 0.8 == 80% 0.01 === 1% 1 == 100%

Due to supporting both the number as a percent and the number as an integer it's a side-effect.
