### ISSUE TITLE
Add a field under Extra->Modifiers for Effect Range Bonus

### ISSUE THREAD

**Issue by GSV-a-Nest-of-Kindled-Embers** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#79]
Add a field under Extra->Modifiers for Effect Range Bonus:
![image](https://user-images.githubusercontent.com/69528253/110364163-70312380-8011-11eb-91d4-a4bfb166559a.png)

Orders/features can often modify the effect range (i.e., 'target is burned on a 17+', etc.) of a user's moves, and having a field for that would be useful for use by automation scripts.

**Comment by dylanpiera** [comment]
Will be merging this and dealing with it at the same time as #34
