### ISSUE TITLE
Add a field on Pokemon sheets for the type of Pokeball that pokemon is kept in.

### ISSUE THREAD

**Issue by GSV-a-Nest-of-Kindled-Embers** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#82]
Add a field on Pokemon sheets for the type of Pokeball that pokemon is kept in.
Players love to dote over the specifics of what sort of ball they keep their favorite pokemon in, and also, my current graphical project to throw pokeballs upon capture/recall/dragging-onto-field can look even better if I can know what ball sprite to use.

**Comment by dylanpiera** [comment]
You had all the ball sprites downloaded already right? Could you share those?

**Comment by dylanpiera** [comment]
Pokéball field autocomplete currently points to `endsWith("ball")`. Once item categorisation is implemented properly, this can be switched over to item category.
