### ISSUE TITLE
Capabilities/Throwing Mastery

### ISSUE THREAD

**Issue by Cool-Cer** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#87]
Lacking the ability to add modifiers that affect throwing for the edge throwing mastery.

**Comment by GSV-a-Nest-of-Kindled-Embers** [comment]
Adding a 'modifier' field for all of the capabilities for user-entered values to be added in to the final values would be a great addition in general.

**Comment by dylanpiera** [comment]
> Adding a 'modifier' field for all of the capabilities for user-entered values to be added in to the final values would be a great addition in general.

I'm not sure about this one, considering that there are a lot of capabilities and it'd take up a lot of space in the extra tab. If anything it'd be a different menu alltogether.

However I will implement a modifier in the data so it can be edited directly through code or AEs

**Comment by dylanpiera** [comment]
An Active Effect like the following will do just what you need:

![image](https://user-images.githubusercontent.com/2012848/116706414-e75db500-a9cd-11eb-9ca2-b10844997964.png)
